### ISSUE TITLE
Example Projects Compilation Errors

### ISSUE THREAD

**Issue by gencay3535** [AVSystem/Anjay-stm32-azurertos-client#1]
Hello, we are trying to compile the example projects for U585-IOT Kit , here we get the following errors for the SBSFU_Boot Project.

My colleague had this kind of compilation error: 
`Windows_NT
Postbuild with python script
Traceback (most recent call last):
  File "D:\repo\cellular\Anjay-stm32-azurertos-client\Middlewares\Third_Party\mcuboot\scripts\imgtool.py", line 19, in <module>
    import click
ModuleNotFoundError: No module named 'click'
postbuild.sh failed`

When I try to compile the same project I get

`Windows_NT
Postbuild with python script
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
postbuild.sh failed
make[1]: *** [makefile:96: post-build] Error 1
make: *** [makefile:62: all] Error 2
"make -j12 all" terminated with exit code 2. Build might be incomplete.`

Python is installed and can be seen on the path

`PS C:\Users\admin\Desktop\Azure\Anjay-stm32-azurertos-client> $env:PATH
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10262.0_x64__8wekyb3d8bbwe;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\admin\AppData\Local\Programs\Python\Python311\Scripts;C:\Users\admin\AppData\Local\Programs\Python\Python311;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk-19\bin;;C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.1\bin;;C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\bin
PS C:\Users\admin\Desktop\Azure\Anjay-stm32-azurertos-client> python --version
Python 3.11.3`

What are we missing?

**Comment by witekgeb** [comment]
Hi @gencay3535 

For now we only support build process on Linux. We can probably prepare a Windows version by the end of this week. 
I'll let you know when it's ready.

Regards 
Witold

**Comment by witekgeb** [comment]
Hi @gencay3535 

I just updated the repo. In `https://github.com/AVSystem/Anjay-stm32-azurertos-client/blob/main/Projects/B-U585I-IOT02A/README.md` you can find new `Dependencies` section which contain the list of python modules that you need to run the building and flashing process. Furthermore in shell scripts we added PATH for default STM32CubeProgrammer location on Windows.

Regards
Witold

**Comment by gencay3535** [comment]
- Hello @witekgeb  Thank you for the update, I have installed all the dependencies but I had python not found error from the IDE `Projects\B-U585I-IOT02A\SBSFU_Boot\STM32CubeIDE\postbuild.sh` and my output for the python --version is python 3.11 then I made a modification at the postbuild.sh in line 29:
 `-cmd="python3 "
 +cmd="python "
 `
 Now I can compile, would this create a problem for the project?
 
-  My other question is this; This project is based on TF-M or X-CUBE-SBSFU?

**Comment by witekgeb** [comment]
- @gencay3535 our Windows computers recognize `cmd="python3 "` probably due to some additional dependencies on the machine. The correct way on Windows is to call `cmd="python "`. We'll fix that, but for now your modification should be enough.

- We are based our code on the SBSFU example: https://github.com/STMicroelectronics/STM32CubeU5/tree/v1.0.2/Projects/B-U585I-IOT02A/Applications/SBSFU
