### ISSUE TITLE
Hardware / Software Cryptography

### ISSUE THREAD

**Issue by gencay3535** [AVSystem/Anjay-stm32-azurertos-client#2]
For our Custom Board, we are considering STM32U575 MCU which does not have a hardware crypto feature like STM32U585. Would that create a problem with the source code implementation of these example projects? To be franker, I wanted to ask if hardware cryptography is used or not in this project.

**Comment by witekgeb** [comment]
Hi @gencay3535 

In Anjay application mbedtls doesn't use hardware acceleration. However in SBSFU_Boot hardware acceleration is used. To disable it in `/Projects/B-U585I-IOT02A/SBSFU_Boot/Inc/config-boot.h` remove line 33 `#define BL2_HW_ACCEL_ENABLE`.

Best regards
Witold
