### ISSUE TITLE
X-Cube-Cellular version 7.1.0

### ISSUE THREAD

**Issue by gencay3535** [AVSystem/Anjay-stm32-azurertos-client#5]
Hello,
 
X-Cube-Cellular version 7.1.0 is released. Some of the bugs are fixed and there are some new features, so are you planning to upgrade to this release from 7.0.0?

Thank you in advance!

**Comment by witekgeb** [comment]
Hello 

We are planning the upgrade, but without specified date of release. Do you have any problem with current version?

Regards 
Witold

**Comment by gencay3535** [comment]
No, not encountered any errors yet, just wanted to know because there have been bug fixes with the new version.
