### ISSUE TITLE
STM32CubeU5 MCU Firmware Package

### ISSUE THREAD

**Issue by gencay3535** [AVSystem/Anjay-stm32-azurertos-client#6]
Hello, 
Have you used STM32CubeU5 ver 1.1.1 or 1.2.0 because it seems like yours is differing from the standard? I wanted to know which one you have used as a baseline and if is it stable if you used ver 1.1.1. 
Thank you in advance!

**Comment by witekgeb** [comment]
Hello 

We are using STM32Cube FW_U5 **v1.1.1** in this project. 

Regards
Witold
